/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M10
 * Generated at: 2016-10-07 14:54:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.content;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class addNewBook_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/struts2-core-2.5.2.jar", Long.valueOf(1472021682000L));
    _jspx_dependants.put("jar:file:/Users/admin/Desktop/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/test2/WEB-INF/lib/struts2-core-2.5.2.jar!/META-INF/struts-tags.tld", Long.valueOf(1467859878000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("\t<title>书目查询系统</title>\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"style/register-login.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div id=\"box\"></div>\n");
      out.write("<div class=\"cent-box register-box\">\n");
      out.write("\t<div class=\"cent-box-header\">\n");
      out.write("\t\t<h1 class=\"main-title hide\">lab2</h1>\n");
      out.write("\t\t<h2 class=\"sub-title\">樊昱才lab2 - BookDB System</h2>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<div class=\"cont-main clearfix\">\n");
      out.write("\t\t<div class=\"index-tab\">\n");
      out.write("\t\t\t<div class=\"index-slide-nav\">\n");
      out.write("\t\t\t\t<a href=searchResult>查询</a>\n");
      out.write("\t\t\t\t<a href=addNewWhat class=\"active\">添加</a>\n");
      out.write("\t\t\t\t<a href=updateBook>编辑</a>\n");
      out.write("\t\t\t\t<div class=\"slide-bar slide-bar1\"></div>\t\t\t\t\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<form action=\"AddNewBook.action\" method=\"post\">\n");
      out.write("\t\t\n");
      out.write("\t\t<div class=\"login form\">\n");
      out.write("\t\t\t<div class=\"group\">\n");
      out.write("\t\t\t\t<div class=\"group-ipt bookISBN\">\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"isbn\" id=\"email\" class=\"ipt\" placeholder=\"图书ISBN编号\" required>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"group-ipt bookTitle\">\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"title\" id=\"user\" class=\"ipt\" placeholder=\"图书名目\" required>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"group-ipt authorID\">\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"authorid\" id=\"user\" class=\"ipt\" placeholder=\"作者ID\" required>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"group-ipt bookPublisher\">\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"publisher\" id=\"user\" class=\"ipt\" placeholder=\"图书出版商\" required>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"group-ipt bookDate\">\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"publishdate\" id=\"user\" class=\"ipt\" placeholder=\"图书出版日期\" required>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"group-ipt bookPrice\">\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"price\" id=\"user\" class=\"ipt\" placeholder=\"图书价格\" required>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t<div class=\"button\">\n");
      out.write("\t\t\t<button type=\"submit\" class=\"login-btn register-btn\" id=\"button\">添加图书并保存</button>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t</form>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!-- background -->\n");
      out.write("<div class=\"footer\">\n");
      out.write("\t<p>lab2 - 樊昱才 1140320213</p>\n");
      out.write("</div>\n");
      out.write("<script src='js/particles.js' type=\"text/javascript\"></script>\n");
      out.write("<script src='js/background.js' type=\"text/javascript\"></script>\n");
      out.write("<script src='js/jquery.min.js' type=\"text/javascript\"></script>\n");
      out.write("<script src='js/layer/layer.js' type=\"text/javascript\"></script>\n");
      out.write("<script src='js/index.js' type=\"text/javascript\"></script>\n");
      out.write("<!-- background -->\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
